name: ci

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Echo Run Ch1 folder
        run: |
          for file in $(ls ./ch1/*.go | sort -V); do
            echo "Running $file"
            go run "$file"
            echo
          done
      - name: Echo Run Ch2 folder
        run: |
          for file in $(ls ./ch2/*.go | sort -V); do
            echo "Running $file"
            go run "$file"
            echo
          done
      - name: Echo Run Ch2 folder
        run: |
          for file in $(ls ./ch3/*.go | sort -V); do
            echo "Running $file"
            go run "$file"
            echo
          done
