name: ci

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Echo Run Ch1 folder
        run: |
          for file in $(ls ./ch1/*.go | sort -V); do
            echo "Running $file"
            go run "$file"
            echo
          done
      - name: Echo Run Ch2 folder
        run: |
          for file in $(ls ./ch2/*.go | sort -V); do
            echo "Running $file"
            go run "$file"
            echo
          done
      - name: Echo Run Ch3 folder
        run: |
          for file in $(ls ./ch3/*.go | sort -V); do
            echo "Running $file"
            go run "$file"
            echo
          done
      - name: Echo Run Ch3 subfolders
        run: |
          for folder in $(ls -d ./ch3/*/ | sort -V); do
            echo "Entering folder $folder"
            
            # Check if go.mod exists in the folder before initializing
            if [ ! -f "$folder/go.mod" ]; then
              echo "Init Go Mod in $folder"
              cd "$folder" && go mod init "$(basename "$folder")"
              cd -  # Go back to the previous directory
            fi
            
            # Run tests once per folder, not per file
            echo "Running tests in $folder"
            cd "$folder" && go test -v ./...
            cd -  # Go back to the previous directory
            
            echo
          done


